# Generated by Django 5.0.4 on 2024-04-24 18:12

import datetime
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('publish', django_ckeditor_5.fields.CKEditor5Field(blank=True)),
                ('date', models.DateField(verbose_name=datetime.date.today)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
    ]
