# Generated by Django 5.0.4 on 2024-04-24 02:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posted', '0005_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
